name: Pandoc builds

on: push

jobs:
  pandoc:
    runs-on: ubuntu-22.04
    steps:
      - name: Create build directory
        run: mkdir build
      - name: Checkout
        uses: actions/checkout@v3
      - uses: docker://pandoc/latex:2.9
        with:
          args: samenvatting.md -o build/samenvatting.pdf
      - uses: docker://pandoc/latex:2.9
        with:
          args: --output=build/begrippen.pdf begrippen.md
      - name: Release pandoc generated pdfs
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/samenvatting.pdf
            build/begrippen.pdf