name: Presentatie

on: push

env:
  BUILD_DIR: build
  PRESENTATIE_DIR: build/presentatie
  LANG: "nl_NL.UTF-8"
  MARP_USER: "1001:115"

jobs:
  marp:
    runs-on: ubuntu-latest
    steps:
      - name: Generate dutch
        run: sudo locale-gen nl_NL.UTF-8
      - name: Checkout 
        uses: actions/checkout@v3
      - name: Prepare
        run: make prepare
      # - name: loosen permissions
      #   run: chmod g+wx,o+wx build/presentatie/img
      - name: Diagram
        run: make diagram
      - name: Run makefile target presentatie
        run: make presentatie
      - name: Deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./${{ env.PRESENTATIE_DIR }}
      - name: Release presentatie.zip
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.BUILD_DIR }}/presentatie.zip
