name: Prints

on: push

env:
  BUILD_DIR: build
  PRINT_DIR: ${{ env.BUILD_DIR }}/print
  
jobs:
  pandoc:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Make print
        run: make print
      - name: Release pandoc generated pdfs
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ env.PRINT_DIR }}/hoe-de-cursus-te-volgen.pdf
            ${{ env.PRINT_DIR }}/samenvatting.pdf
            ${{ env.PRINT_DIR }}/begrippen.pdf
            ${{ env.PRINT_DIR }}/begrippen-per-onderdeel.pdf
            ${{ env.PRINT_DIR }}/oefeningen.pdf
            ${{ env.PRINT_DIR }}/sneltoetsen-per-onderdeel.pdf
            ${{ env.PRINT_DIR }}/verder-leren.pdf
            ${{ env.BUILD_DIR }}/prepare-education-box.sh
